// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20250306081006_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.Accomodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccomodationType")
                        .HasColumnType("integer");

                    b.Property<bool>("DisabledFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPool")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSpa")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Accomodations");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.AccomodationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccomodationId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaximumGuests")
                        .HasColumnType("integer");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationId");

                    b.ToTable("AccomodationUnits");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.Arrangement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccomodationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ArrangementType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("MaximumPassengers")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MeetingPlaceId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("MeetingTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TransportationType")
                        .HasColumnType("integer");

                    b.Property<string>("TravelProgramme")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationId");

                    b.HasIndex("MeetingPlaceId");

                    b.ToTable("Arrangements");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArrangementId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommentText")
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArrangementId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.MeetingPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<string>("Longitude")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("MeetingPlaces");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccomodationUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArrangementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationUnitId");

                    b.HasIndex("ArrangementId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.AccomodationUnit", b =>
                {
                    b.HasOne("Learning_DotNet.Core.Domain.Entities.Accomodation", null)
                        .WithMany("AccomodationUnits")
                        .HasForeignKey("AccomodationId");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.Arrangement", b =>
                {
                    b.HasOne("Learning_DotNet.Core.Domain.Entities.Accomodation", "Accomodation")
                        .WithMany()
                        .HasForeignKey("AccomodationId");

                    b.HasOne("Learning_DotNet.Core.Domain.Entities.User", null)
                        .WithMany("CreatedArrangements")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learning_DotNet.Core.Domain.Entities.MeetingPlace", "MeetingPlace")
                        .WithMany()
                        .HasForeignKey("MeetingPlaceId");

                    b.Navigation("Accomodation");

                    b.Navigation("MeetingPlace");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Learning_DotNet.Core.Domain.Entities.Arrangement", "Arrangement")
                        .WithMany()
                        .HasForeignKey("ArrangementId");

                    b.HasOne("Learning_DotNet.Core.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Arrangement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.MeetingPlace", b =>
                {
                    b.HasOne("Learning_DotNet.Core.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Learning_DotNet.Core.Domain.Entities.AccomodationUnit", "AccomodationUnit")
                        .WithMany()
                        .HasForeignKey("AccomodationUnitId");

                    b.HasOne("Learning_DotNet.Core.Domain.Entities.Arrangement", "Arrangement")
                        .WithMany()
                        .HasForeignKey("ArrangementId");

                    b.HasOne("Learning_DotNet.Core.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId");

                    b.Navigation("AccomodationUnit");

                    b.Navigation("Arrangement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.Accomodation", b =>
                {
                    b.Navigation("AccomodationUnits");
                });

            modelBuilder.Entity("Learning_DotNet.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedArrangements");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
