version: '3.8'

services:
    kc_db:
        image: postgres:latest
        container_name: kc_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: kc_db
        volumes:
        - ./kc-db:/var/lib/postgresql/data:rw
        ports:
        - "5432:5432"

    app_db:
        image: postgres:latest
        container_name: app_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: app_db
        volumes:
        - ./app-db:/var/lib/postgresql/data:rw
        ports:
        - "5433:5432"

    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:latest
        command: start
        volumes:
        - ./keycloak:/opt/keycloak/data/
        environment:
            KC_HOSTNAME: localhost
            KC_HOSTNAME_PORT: 8080
            KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
            KC_HTTP_ENABLED: "true"
            KC_HOSTNAME_STRICT_HTTPS: "false"
            KC_HEALTH_ENABLED: "true"
            KEYCLOAK_ADMIN: keycloak
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://kc_db:5432/kc_db
            KC_DB_USERNAME: postgres
            KC_DB_PASSWORD: admin
        ports:
            - 7080:8080
        restart: always
volumes:
    kc-db:
    app-db:
    keycloak:
